# ğŸŒ™ NekoBedWars é…ç½®æ–‡ä»¶ âœ§ äºŒæ¬¡å…ƒå¹»æƒ³ç‰ˆ âœ§
# å–µï½æ¬¢è¿æ¥åˆ°æ¢¦å¹»æ¬¡å…ƒçš„èµ·åºŠæˆ˜äº‰ä¸–ç•Œï¼
# å¯çˆ±æ˜¯åŠ›é‡ï¼Œä¿¡ä»°æ˜¯èƒœåˆ© à¸…(â‰šá„Œâ‰š)~â™¡
#
# ğŸ¾ æ•°æ®åº“é…ç½®
database:
  type: MySQL
  mysql:
    host: localhost
    port: 3306
    database: nekobedwars
    username: root
    password: wcjs123
arena:
  name: å½¼å²¸
  world: World
  beds:
    red: -67.0,64.0,1.0
    green: 66.0,64.0,1.0
    blue: 0.0,64.0,-66.0
    yellow: 0.0,64.0,67.0
  spawns:
    red: -79.0,62.0,1.0
    green: 78.0,62.0,1.0
    blue: 0.0,62.0,-78.0
    yellow: 0.0,62.0,80.0
  shops:
    - -79.0,62.0,7.0
    - -6.0,62.0,81.0
    - 80.0,63.0,8.0
    - 7.0,63.0,-79.0
  upgrades:
    - -79.0,62.0,-5.0
    - 6.0,62.0,80.0
    - 79.0,63.0,-6.0
    - -7.0,63.0,-78.0
  waitingarea:
    pos1: 12.204299817818505,127.60564412531888,12.932838162517566
    pos2: -10.174967683224907,112.99009138452796,-10.931412867034023
  maxplayers: 4
  teams:
    - red
    - green
    - blue
    - yellow
  waitingspawn: 0.5677654917165047,118.0,0.5062195591216321
  resources:
    diamond:
      - -44.0,63.0,48.0
      - 47.0,63.0,45.0
      - 44.0,63.0,-46.0
      - -47.0,63.0,-43.0
    iron:
      - -83.0,62.0,2.0
      - -83.0,62.0,1.0
      - -83.0,62.0,0.0
      - 1.0,62.0,84.0
      - 0.0,62.0,84.0
      - -1.0,62.0,84.0
      - 83.0,62.0,0.0
      - 83.0,62.0,1.0
      - 83.0,62.0,2.0
      - -1.0,62.0,-82.0
      - 0.0,62.0,-82.0
      - 1.0,62.0,-82.0
    emerald:
      - 0.0,64.0,1.0
      - 0.0,83.0,1.0
effects:
  bed_destroy:
    type: REDSTONE
    color: LIGHT_PINK
  player_death:
    type: CLOUD
  resource_generate:
    type: SPELL_MOB_AMBIENT
sounds:
  bed_destroy:
    type: ENTITY_ENDERDRAGON_GROWL
    volume: 1.2
    pitch: 1.0
  player_death:
    type: ENTITY_CAT_HURT
    volume: 1.0
    pitch: 1.2
  game_start:
    type: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 1.8
  game_end:
    type: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.5
scoreboard:
  title: '&dâœ¦ &b&læ¢¦å¹»æ¬¡å…ƒ &dâœ¦'
  lines:
    - '&r&fåœ°å›¾: &d{arena}'
    - '&fç©å®¶: &b{players}&7/&b{maxplayers}'
    - '&fé˜Ÿä¼: &a{teams}'
    - '&fçŠ¶æ€: &e{gamestate}'
    - ''
    - '&fåºŠå‰©ä½™: &c{beds_remaining}'
    - '&få‡»æ€æ•°: &e{kills}'
    - ''
    - '&dâœ§ &bä¸ºä¿¡ä»°è€Œæˆ˜å–µ~! &dâœ§'
    - '&fPowered by &dNekoTeamâ˜†'
  waiting-title: '&6&lç­‰å¾…å¤§å…'
  waiting-lines:
    - '&fåœ°å›¾: &a{arena}'
    - '&fç©å®¶: &b{players}&7/&b{maxplayers}'
    - ''
    - '&eç­‰å¾…å…¶ä»–ç©å®¶åŠ å…¥...'
    - '&fè¿˜éœ€è¦ &c{playersneeded} &fåç©å®¶'
    - ''
    - '&dâœ§ &bä¸ºä¿¡ä»°è€Œæˆ˜å–µ~! &dâœ§'
    - '&fPowered by &dNekoTeamâ˜†'
game:
  countdown: 30
  restart-time: 10
arena:
  configured: false
